In [1]:

import pygame
import random
import os
import time
import numpy as np
import math
import torch
import torch.nn.functional
import matplotlib.pyplot as plt
import torch.optim as opt
from torch.autograd import Variable
from sklearn.model_selection import train_test_split

import scipy.stats as st
from sklearn.datasets.samples_generator import make_blobs
from matplotlib.colors import LogNorm 
import matplotlib.cm as cm
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
from scipy.interpolate import griddata
if torch.cuda.is_available():  
    dev = "cuda:0" 
else:  
    dev = "cpu"  

print(dev)



pygame 2.0.1 (SDL 2.0.14, Python 3.8.3)
Hello from the pygame community. https://www.pygame.org/contribute.html


D:\ComputerSoftwares\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.datasets.samples_generator module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.datasets. Anything that cannot be imported from sklearn.datasets is now part of the private API.
  warnings.warn(message, FutureWarning)


cuda:0


In [2]:
global temp_list
temp_list = []
Agent_number_n=5;

In [3]:
def appen(_x_list,y):
    global temp_list
    temp_list.append(_x_list)
    
def appen_train(x_list):
    global temp_list
                
    S= max(sum(x_list),1.0);
    temp_list = []
    
    for i in range(Agent_number_n):
        temp = []
        for j in range(Agent_number_n):
            if(i!=j):
                temp.append(x_list[j])
        appen(temp,S)
    
    training_data.append(temp_list)
    training_label.append(S)
    

def read_training_data():
    for i in range(100000):
        appen_train(sorted(np.random.rand(Agent_number_n), reverse=True));

training_data=[]
training_label=[]
S=1.0
read_training_data();

def appen_test(x_list):
    global temp_list
                
    S= max(sum(x_list),1.0);
    temp_list = []
    
    for i in range(Agent_number_n):
        temp = []
        for j in range(Agent_number_n):
            if(i!=j):
                temp.append(x_list[j])
        appen(temp,S)
    testing_data.append(temp_list)
    testing_label.append(S)
    

def read_testing_data():
    for i in range(100000):
        appen_test(sorted(np.random.rand(Agent_number_n), reverse=True));
                            

testing_data=[]
testing_label=[]
S=1.0
read_testing_data();

training_data=np.array(training_data)
training_label=np.array(training_label)
testing_data=np.array(testing_data)
testing_label=np.array(testing_label)
print(training_data)
print(testing_data)
print(training_label)
print(testing_label)

[[[0.7209953  0.69745304 0.6857042  0.53372662]
  [0.77915377 0.69745304 0.6857042  0.53372662]
  [0.77915377 0.7209953  0.6857042  0.53372662]
  [0.77915377 0.7209953  0.69745304 0.53372662]
  [0.77915377 0.7209953  0.69745304 0.6857042 ]]

 [[0.7799582  0.40892628 0.37844312 0.11479999]
  [0.87244332 0.40892628 0.37844312 0.11479999]
  [0.87244332 0.7799582  0.37844312 0.11479999]
  [0.87244332 0.7799582  0.40892628 0.11479999]
  [0.87244332 0.7799582  0.40892628 0.37844312]]

 [[0.51763593 0.22039018 0.09939943 0.09436559]
  [0.89361847 0.22039018 0.09939943 0.09436559]
  [0.89361847 0.51763593 0.09939943 0.09436559]
  [0.89361847 0.51763593 0.22039018 0.09436559]
  [0.89361847 0.51763593 0.22039018 0.09939943]]

 ...

 [[0.6936404  0.42942362 0.15212467 0.12759672]
  [0.89501331 0.42942362 0.15212467 0.12759672]
  [0.89501331 0.6936404  0.15212467 0.12759672]
  [0.89501331 0.6936404  0.42942362 0.12759672]
  [0.89501331 0.6936404  0.42942362 0.15212467]]

 [[0.88504522 0.78458777 0

In [4]:
def h_3_star(a, b, t):
    return a - min(a, t) + b - min(b, t) + max(min(a, t)+min(b, t), 2*t/3) + 1/2 * max(min(a, t)+min(b, t), t) - 1/2 * max(max(min(a, t), min(b, t)), 2*t/3) - t/6


def f_function(a, b, z):
    if(z >= 1):
        return (a+b)/2 + z/3
    else:
        return z/3 + h_3_star(a, b, 1-z)/2

def h_function(input_list):
    #input_list = sorted(input_list)
    g_list = []
    for j1 in range(len(input_list) ):
        for j2 in range(len(input_list)):
            if(j1 != j2):
                a = input_list[j1]
                b = input_list[j2]
                z = sum(input_list)- a-b

                g_list.append( f_function(a, b, z) * (Agent_number_n-1))
    h = sum(g_list) * 3 /  (Agent_number_n) /  (Agent_number_n-1) /  (Agent_number_n - 2)
    return h
                
                
x_list = []
y_list = []
z_list = []
result_list = []
training_supervised_label=[]
for index in range(len(training_data)):
    h_list = []
    for i in range(Agent_number_n):
        x_list.append(training_data[index][i][0])
        y_list.append(training_data[index][i][1])
        h = h_function(training_data[index][i])
        z_list.append(float(h))
        h_list.append(float(h))
    training_supervised_label.append(h_list)
    result_list.append(sum(h_list)/training_label[index]) 
    
    
print(max(result_list), min(result_list), max(result_list)-min(result_list),sum(result_list)/len(result_list))

4.386197629985663 3.9999999999999982 0.38619762998566465 4.068447644857674


In [5]:
# def h_function(input_list):

#     h = max(sum(input_list),2/3) + 1/2 * max(sum(input_list),1) - 1/2 * max(input_list[0],2/3) - 1/6
#     return h

def h_function(input_list):
    if(sum(input_list)>=(Agent_number_n-1)/Agent_number_n):
        h = sum(input_list)
    else:
        h = (Agent_number_n-1)/Agent_number_n
    return h   
                
result_list = []
for index in range(len(training_data)):
    h_list = []
    for i in range(Agent_number_n):
        h = h_function(training_data[index][i])
        h_list.append(float(h))
    result_list.append(sum(h_list)/training_label[index]) 
    
    
print(max(result_list), min(result_list), max(result_list)-min(result_list),sum(result_list)/len(result_list))

4.704485854087544 3.9999999999999982 0.7044858540875456 4.006366451890246


In [7]:
# def h_function(input_list):

#     h = max(sum(input_list),2/3) + 1/2 * max(sum(input_list),1) - 1/2 * max(input_list[0],2/3) - 1/6
#     return h
def h_function(input_list):

    h = (Agent_number_n-1)/(Agent_number_n*2)*max(sum(input_list),1) + (Agent_number_n-1)/Agent_number_n * max(sum(input_list),1/2) - 1.0/Agent_number_n * max(input_list[0],1/2) - 1.0/Agent_number_n
    return h  
                
result_list = []
for index in range(len(training_data)):
    h_list = []
    for i in range(Agent_number_n):
        h = h_function(training_data[index][i])
        h_list.append(float(h))
    result_list.append(sum(h_list)/training_label[index]) 
    
    
print(max(result_list), min(result_list), max(result_list)-min(result_list),sum(result_list)/len(result_list))

4.381143171895169 2.5 1.881143171895169 4.0415577363379205
