In [1]:

import pygame
import random
import os
import time
import numpy as np
import math
import torch
import torch.nn.functional
import matplotlib.pyplot as plt
import torch.optim as opt
from torch.autograd import Variable
from sklearn.model_selection import train_test_split

import scipy.stats as st
from sklearn.datasets.samples_generator import make_blobs
from matplotlib.colors import LogNorm 
import matplotlib.cm as cm
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt


if torch.cuda.is_available():  
    dev = "cuda:0" 
else:  
    dev = "cpu"  

print(dev)


pygame 2.0.1 (SDL 2.0.14, Python 3.8.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
cuda:0


D:\ComputerSoftwares\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.datasets.samples_generator module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.datasets. Anything that cannot be imported from sklearn.datasets is now part of the private API.
  warnings.warn(message, FutureWarning)


In [2]:
global temp_list
temp_list = []
Agent_number_n=4;
Alpha = 0.666;



In [3]:
global temp_list
temp_list = []
def appen(_x_list,y):
    global temp_list
    temp_list.append(_x_list)
    
def appen_train(x_list):
    global temp_list
                
    S= max(sum(x_list),1.0);
    temp_list = []
    
    for i in range(Agent_number_n):
        temp = []
        for j in range(Agent_number_n):
            if(i!=j):
                temp.append(x_list[j])
        appen(temp,S)
    
    training_data.append(temp_list)
    training_label.append(S)
    

def read_training_data():
    for i in range(100000):
        appen_train(sorted(np.random.rand(Agent_number_n), reverse=True));

training_data=[]
training_label=[]
S=1.0
read_training_data();

def appen_test(x_list):
    global temp_list
                
    S= max(sum(x_list),1.0);
    temp_list = []
    
    for i in range(Agent_number_n):
        temp = []
        for j in range(Agent_number_n):
            if(i!=j):
                temp.append(x_list[j])
        appen(temp,S)
    testing_data.append(temp_list)
    testing_label.append(S)
    

def read_testing_data():
#     devided=20
#     for i1 in range(devided+1):
#         for i2 in range(i1+1):
#             for i3 in range(i2+1):
#                 appen_test(i1/devided,i2/devided,i3/devided);
    for i in range(100000):
        appen_test(sorted(np.random.rand(Agent_number_n), reverse=True));
                            

testing_data=[]
testing_label=[]
S=1.0
read_testing_data();

training_data=np.array(training_data)
training_label=np.array(training_label)
testing_data=np.array(testing_data)
testing_label=np.array(testing_label)
print(training_data)
print(testing_data)
print(training_label)
print(testing_label)

[[[0.4100703  0.16713258 0.15688668]
  [0.70870741 0.16713258 0.15688668]
  [0.70870741 0.4100703  0.15688668]
  [0.70870741 0.4100703  0.16713258]]

 [[0.76482611 0.56706249 0.24300791]
  [0.87599273 0.56706249 0.24300791]
  [0.87599273 0.76482611 0.24300791]
  [0.87599273 0.76482611 0.56706249]]

 [[0.79892946 0.58188895 0.16594584]
  [0.83185056 0.58188895 0.16594584]
  [0.83185056 0.79892946 0.16594584]
  [0.83185056 0.79892946 0.58188895]]

 ...

 [[0.47895193 0.31750909 0.25290459]
  [0.87421405 0.31750909 0.25290459]
  [0.87421405 0.47895193 0.25290459]
  [0.87421405 0.47895193 0.31750909]]

 [[0.89949009 0.21194944 0.13549105]
  [0.95996973 0.21194944 0.13549105]
  [0.95996973 0.89949009 0.13549105]
  [0.95996973 0.89949009 0.21194944]]

 [[0.6478121  0.51985214 0.04811184]
  [0.94620768 0.51985214 0.04811184]
  [0.94620768 0.6478121  0.04811184]
  [0.94620768 0.6478121  0.51985214]]]
[[[0.77719475 0.73858866 0.32631081]
  [0.89791399 0.73858866 0.32631081]
  [0.89791399 0.7771

In [4]:
print(training_data[:,1])

[[0.70870741 0.16713258 0.15688668]
 [0.87599273 0.56706249 0.24300791]
 [0.83185056 0.58188895 0.16594584]
 ...
 [0.87421405 0.31750909 0.25290459]
 [0.95996973 0.21194944 0.13549105]
 [0.94620768 0.51985214 0.04811184]]


In [7]:
def kernelTrans(X, A, kTup):
    """
    Function：   核转换函数

    Input：      X：数据集
                A：某一行数据
                kTup：核函数信息

    Output： K：计算出的核向量
    """ 
    #获取数据集行列数
    m, n = np.shape(X)
    #初始化列向量
    K = np.mat(np.zeros((m, 1)))
    #根据键值选择相应核函数
    #lin表示的是线性核函数
    if kTup[0] == 'lin': K = X * A.T
    #rbf表示径向基核函数
    elif kTup[0] == 'rbf':
        for j in range(m):
            deltaRow = X[j,:] - A
            K[j] = np.deltaRow * np.deltaRow.T
        #对矩阵元素展开计算，而不像在MATLAB中一样计算矩阵的逆
        K =  exp(K/(-1*kTup[1]**2))
    #如果无法识别，就报错
    else: raise NameError('Houston We Have a Problem -- That Kernel is not recognized')
    #返回计算出的核向量
    return K


In [8]:
k = kernelTrans(training_data, training_data[:,1], 'lin')

ValueError: too many values to unpack (expected 2)