In [1]:
"""
The classic game of flappy bird. Make with python
and pygame. Features pixel perfect collision using masks :o
Date Modified:  Jul 30, 2019
Author: Tech With Tim
Estimated Work Time: 5 hours (1 just for that damn collision)
"""
import pygame
import random
import os
import time
import numpy as np
import math
import torch
import torch.nn.functional
import matplotlib.pyplot as plt
import torch.optim as opt
from torch.autograd import Variable
from sklearn.model_selection import train_test_split

import scipy.stats as st
from sklearn.datasets.samples_generator import make_blobs
from matplotlib.colors import LogNorm 
import matplotlib.cm as cm

pygame 2.0.1 (SDL 2.0.14, Python 3.8.3)
Hello from the pygame community. https://www.pygame.org/contribute.html


D:\ComputerSoftwares\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.datasets.samples_generator module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.datasets. Anything that cannot be imported from sklearn.datasets is now part of the private API.
  warnings.warn(message, FutureWarning)


In [2]:
Agent_number_n=3;
Alpha = (1-0.667);

global temp_list
temp_list = []
def appen(_x_list,y):
    global temp_list
    temp_list.append(_x_list)
    
def appen_train(x_list):
    global temp_list
                
    S= max(sum(x_list),1.0);
    temp_list = []
    
    for i in range(Agent_number_n):
        temp = []
        for j in range(Agent_number_n):
            if(i!=j):
                temp.append(x_list[j])
        appen(temp,S)
    
    training_data.append(temp_list)
    training_label.append(S)
    

def read_training_data():
    for i in range(10000):
        appen_train(np.random.rand(Agent_number_n));

training_data=[]
training_label=[]
S=1.0
read_training_data();

def appen_test(x_list):
    global temp_list
                
    S= max(sum(x_list),1.0);
    temp_list = []
    
    for i in range(Agent_number_n):
        temp = []
        for j in range(Agent_number_n):
            if(i!=j):
                temp.append(x_list[j])
        appen(temp,S)
    testing_data.append(temp_list)
    testing_label.append(S)
    

def read_testing_data():
#     devided=20
#     for i1 in range(devided+1):
#         for i2 in range(i1+1):
#             for i3 in range(i2+1):
#                 appen_test(i1/devided,i2/devided,i3/devided);
    for i in range(10000):
        appen_test(np.random.rand(Agent_number_n));
                            

testing_data=[]
testing_label=[]
S=1.0
read_testing_data();

In [3]:
training_data=np.array(training_data)
training_label=np.array(training_label)
testing_data=np.array(testing_data)
testing_label=np.array(testing_label)
print(testing_data)
print(testing_label)

[[[0.69366526 0.58161431]
  [0.98517829 0.58161431]
  [0.98517829 0.69366526]]

 [[0.86032664 0.45487123]
  [0.19279292 0.45487123]
  [0.19279292 0.86032664]]

 [[0.03123068 0.50221592]
  [0.99986887 0.50221592]
  [0.99986887 0.03123068]]

 ...

 [[0.2735121  0.97732722]
  [0.36755064 0.97732722]
  [0.36755064 0.2735121 ]]

 [[0.4327344  0.43601169]
  [0.87295875 0.43601169]
  [0.87295875 0.4327344 ]]

 [[0.81335189 0.55702861]
  [0.74884678 0.55702861]
  [0.74884678 0.81335189]]]
[2.26045786 1.50799079 1.53331548 ... 1.61838995 1.74170484 2.11922727]


In [4]:
def function_re(input_list):
    #print(max(sum(input_list), 2/3))
    return max(sum(input_list), 2/3) + 1/2*max(sum(input_list),1) - 1/2*max(max(input_list[0],input_list[1]), 1)-1/6

x_list = []
y_list = []
z_list = []
result_list = []
for index in range(len(testing_data)):
    h_list = []
    for i in range(Agent_number_n):
        x_list.append(testing_data[index][i][0])
        y_list.append(testing_data[index][i][1])
        h = function_re(testing_data[index][i])
        z_list.append(float(h))
        h_list.append(float(h))
    result_list.append(sum(h_list)/testing_label[index]) 
print(max(result_list), min(result_list), max(result_list)-min(result_list))

2.318023525888721 1.4999999999999996 0.8180235258887216


In [7]:
def function_re1(input_list):
    #print(max(sum(input_list), 2/3))
    return max(sum(input_list), 2/3) + 1/2*max(sum(input_list),1) - 1/2*max(max(input_list[0],input_list[1]), 2/3)-1/6

x_list = []
y_list = []
z_list = []
result_list = []
for index in range(len(testing_data)):
    h_list = []
    for i in range(Agent_number_n):
        x_list.append(testing_data[index][i][0])
        y_list.append(testing_data[index][i][1])
        h = function_re1(testing_data[index][i])
        z_list.append(float(h))
        h_list.append(float(h))
    result_list.append(sum(h_list)/testing_label[index]) 
print(max(result_list), min(result_list), max(result_list)-min(result_list))

2.332812473446335 2.0 0.33281247344633513


In [6]:
def function_re2(input_list):
    #print(max(sum(input_list), 2/3))
    return 5/6* max(sum(input_list), 1) + 2/3*max(sum(input_list),1/2) - 1/3*max(max(input_list[0],input_list[1]), 1/2)-1/3

x_list = []
y_list = []
z_list = []
result_list = []
for index in range(len(testing_data)):
    h_list = []
    for i in range(Agent_number_n):
        x_list.append(testing_data[index][i][0])
        y_list.append(testing_data[index][i][1])
        h = function_re2(testing_data[index][i])
        z_list.append(float(h))
        h_list.append(float(h))
    result_list.append(sum(h_list)/testing_label[index]) 
print(max(result_list), min(result_list), max(result_list)-min(result_list))

2.3331414871322846 2.0 0.33314148713228464
